country:
    pattern:  /
    defaults: { _controller: "OrchestraOrchestraBundle:Country:index" }

country_show:
    pattern:  /{id}/show
    defaults: { _controller: "OrchestraOrchestraBundle:Country:show" }

country_new:
    pattern:  /new
    defaults: { _controller: "OrchestraOrchestraBundle:Country:new" }

country_create:
    pattern:  /create
    defaults: { _controller: "OrchestraOrchestraBundle:Country:create" }
    requirements: { _method: post }

country_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "OrchestraOrchestraBundle:Country:edit" }

country_update:
    pattern:  /{id}/update
    defaults: { _controller: "OrchestraOrchestraBundle:Country:update" }
    requirements: { _method: post }

country_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "OrchestraOrchestraBundle:Country:delete" }
    requirements: { _method: post }
