message:
    pattern:  /
    defaults: { _controller: "OrchestraOrchestraBundle:Message:index" }

message_show:
    pattern:  /{id}/show
    defaults: { _controller: "OrchestraOrchestraBundle:Message:show" }

message_new:
    pattern:  /new
    defaults: { _controller: "OrchestraOrchestraBundle:Message:new" }

message_create:
    pattern:  /create
    defaults: { _controller: "OrchestraOrchestraBundle:Message:create" }
    requirements: { _method: post }

message_new_repondre:
    pattern:  /{id}/new
    defaults: { _controller: "OrchestraOrchestraBundle:Message:newReply" }

message_repondre:
    pattern:  /{id}/repondre
    defaults: { _controller: "OrchestraOrchestraBundle:Message:createReply" }
    requirements: { _method: post }

message_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "OrchestraOrchestraBundle:Message:delete" }
    requirements: { _method: post }
