news:
    pattern:  /
    defaults: { _controller: "OrchestraOrchestraBundle:News:index" }

news_show:
    pattern:  /{id}/show
    defaults: { _controller: "OrchestraOrchestraBundle:News:show" }
    
news_historique:
    pattern:  /historique
    defaults: { _controller: "OrchestraOrchestraBundle:News:historique" }

news_new:
    pattern:  /new
    defaults: { _controller: "OrchestraOrchestraBundle:News:new" }

news_create:
    pattern:  /create
    defaults: { _controller: "OrchestraOrchestraBundle:News:create" }
    requirements: { _method: post }

news_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "OrchestraOrchestraBundle:News:edit" }

news_update:
    pattern:  /{id}/update
    defaults: { _controller: "OrchestraOrchestraBundle:News:update" }
    requirements: { _method: post }

news_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "OrchestraOrchestraBundle:News:delete" }
    requirements: { _method: post }

news_commentaire_create:
    pattern:  /{id}/create/commentaire
    defaults: { _controller: "OrchestraOrchestraBundle:News:createCommentaire" }
    requirements: { _method: post }

news_commentaire_delete:
    pattern:  /{actualite}/{id}/delete/commentaire
    defaults: { _controller: "OrchestraOrchestraBundle:News:deleteCommentaire" }
