user:
    pattern:  /
    defaults: { _controller: "OrchestraOrchestraBundle:User:index" }

user_show:
    pattern:  /{id}/show
    defaults: { _controller: "OrchestraOrchestraBundle:User:show" }

user_new:
    pattern:  /admin/new
    defaults: { _controller: "OrchestraOrchestraBundle:User:new" }

user_create:
    pattern:  /admin/create
    defaults: { _controller: "OrchestraOrchestraBundle:User:create" }
    requirements: { _method: post }

user_edit:
    pattern:  /admin/{id}/edit
    defaults: { _controller: "OrchestraOrchestraBundle:User:edit" }

user_update:
    pattern:  /admin/{id}/update
    defaults: { _controller: "OrchestraOrchestraBundle:User:update" }
    requirements: { _method: post }

user_delete:
    pattern:  /admin/{id}/delete
    defaults: { _controller: "OrchestraOrchestraBundle:User:delete" }
    requirements: { _method: post }
