user_show:
    pattern:  /{id}/show
    defaults: { _controller: "OrchestraOrchestraBundle:User:show" }

user_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "OrchestraOrchestraBundle:User:edit" }

user_update:
    pattern:  /{id}/update
    defaults: { _controller: "OrchestraOrchestraBundle:User:update" }
    requirements: { _method: post }

user_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "OrchestraOrchestraBundle:User:delete" }
    requirements: { _method: get }
    
user_avatar:
  pattern: /{id}/avatar
  defaults: { _controller: OrchestraOrchestraBundle:User:avatar }
