user:
    pattern:  /{sort}/{by}
    defaults: { _controller: "OrchestraOrchestraBundle:User:index", sort: firstname, by: asc }
    requirements:
        sort: firstname|lastname|classe|username
        by: asc|desc

user_show:
    pattern:  /{id}/show
    defaults: { _controller: "OrchestraOrchestraBundle:User:show" }

user_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "OrchestraOrchestraBundle:User:edit" }

user_update:
    pattern:  /{id}/update
    defaults: { _controller: "OrchestraOrchestraBundle:User:update" }
    requirements: { _method: post }

user_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "Bundle:User:delete" }
    requirements: { _method: post }
    
user_search:
  pattern: /rechercher
  defaults: { _controller: OrchestraOrchestraBundle:User:rechercher }
  requirements:
    _method: POST
    
user_avatar:
  pattern: /{id}/avatar
  defaults: { _controller: OrchestraOrchestraBundle:User:avatar }
