imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: fr }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  fr_FR
    trust_proxy_headers: false # Whether or not the Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:
        #lifetime:       900

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        default_connection : default
        connections:
            default:
                 driver:   %database_driver%
                 host:     %database_host%
                 port:     %database_port%
                 dbname:   %database_name%
                 user:     %database_user%
                 password: %database_password%
                 charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        entity_managers:
            default:
                auto_mapping: true
                mappings:
                      ApplicationSonataMediaBundle: ~

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Orchestra\OrchestraBundle\Entity\User
    
knp_paginator:
    default_options:
        sort_field_name:      sort
        sort_direction_name:  direction
        page_name:            page
        distinct:             true
    template:
        pagination:           KnpPaginatorBundle:Pagination:sliding.html.twig
        sortable:             KnpPaginatorBundle:Pagination:sortable_link.html.twig
    page_range:           5

genemu_form:
    captcha:
        enabled:          true
        width:            100
        height:           40
        length:           4
        format:           'png'
        chars:            '0123456789'
        font_size:        18
        font_color:       ['252525', '8B8787', '550707', '3526E6', '88531E']
        font_dir:         %kernel.root_dir%/../web/bundles/genemuform/fonts
        fonts:            ['akbar.ttf', 'brushcut.ttf', 'molten.ttf', 'planetbe.ttf', 'whoobub.ttf']
        background_color: 'DDDDDD'
        border_color:     '000000'
        grayscale:        false
    select2: ~
    date: ~
    autocomplete: ~
    image:
        enabled:  true
        selected: 'large'
        filters:  ['rotate', 'bw', 'negative', 'sepia', 'crop']
        thumbnails:
            small:  [100, 100]
            medium: [200, 200]
            large:  [500, 500]
            extra:  [1024, 768]
    file:
        swf: /uploadify/uploadify.swf
        enabled:    true
        cancel_img: '/bundes/genemuform/images/cancel.png'
        folder:     '/upload'
            
sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
 
        #sonata.admin_doctrine_orm.block.audit:
        #    contexts:   [admin]
 
        sonata.block.service.text:
        sonata.block.service.action:
        sonata.block.service.rss:
 
        # Some specific block from the SonataMediaBundle
        #sonata.media.block.media:
        #sonata.media.block.gallery:
        #sonata.media.block.feature_media:     
          
sonata_admin:
    title:      Orchestra
    title_logo: bundles/sonataadmin/logo_title.png
    
    templates:
        # default global templates
        layout:  SonataAdminBundle::standard_layout.html.twig
        ajax:    SonataAdminBundle::ajax_layout.html.twig
 
        # default actions templates, should extend a global templates
        list:    SonataAdminBundle:CRUD:list.html.twig
        show:    SonataAdminBundle:CRUD:show.html.twig
        edit:    SonataAdminBundle:CRUD:edit.html.twig
        history: SonataAdminBundle:CRUD:history.html.twig
        preview: SonataAdminBundle:CRUD:preview.html.twig
        delete:  SonataAdminBundle:CRUD:delete.html.twig

        # default values of helper templates
        short_object_description: SonataAdminBundle:Helper:short-object-description.html.twig

        # default values of block templates, they should extend the base_block template
        list_block: SonataAdminBundle:Block:block_admin_list.html.twig
        
    dashboard:
        blocks:
            # display a dashboard block
            - { position: left, type: sonata.admin.block.admin_list }

            # Customize this part to add new block configuration
            #- { position: right, type: sonata.block.service.text, settings: { content: "<h2>Welcome to the Sonata Admin</h2> <p>This is a <code>sonata.block.service.text</code> from the Block Bundle, you can create and add new block in these area by configuring the <code>sonata_admin</code> section.</p> <br /> For instance, here a RSS feed parser (<code>sonata.block.service.rss</code>):"} }
            #- { position: right, type: sonata.block.service.rss, settings: { title: Sonata Project's Feeds, url: http://sonata-project.org/blog/archive.rss }}
 
        groups:
            orchestra:
                label: users  
            mediatheque:
                label: mediatheque  
            galerie:
                label: galerie  
                
sonata_doctrine_orm_admin:
    # default value is null, so doctrine uses the value defined in the configuration
    entity_manager: ~

    templates:
        form:
            - SonataDoctrineORMAdminBundle:Form:form_admin_fields.html.twig
        filter:
            - SonataDoctrineORMAdminBundle:Form:filter_admin_fields.html.twig
        types:
            list:
                array:      SonataAdminBundle:CRUD:list_array.html.twig
                boolean:    SonataAdminBundle:CRUD:list_boolean.html.twig
                date:       SonataAdminBundle:CRUD:list_date.html.twig
                time:       SonataAdminBundle:CRUD:list_time.html.twig
                datetime:   SonataAdminBundle:CRUD:list_datetime.html.twig
                text:       SonataAdminBundle:CRUD:base_list_field.html.twig
                trans:      SonataAdminBundle:CRUD:list_trans.html.twig
                string:     SonataAdminBundle:CRUD:base_list_field.html.twig
                smallint:   SonataAdminBundle:CRUD:base_list_field.html.twig
                bigint:     SonataAdminBundle:CRUD:base_list_field.html.twig
                integer:    SonataAdminBundle:CRUD:base_list_field.html.twig
                decimal:    SonataAdminBundle:CRUD:base_list_field.html.twig
                identifier: SonataAdminBundle:CRUD:base_list_field.html.twig

            show:
                array:      SonataAdminBundle:CRUD:show_array.html.twig
                boolean:    SonataAdminBundle:CRUD:show_boolean.html.twig
                date:       SonataAdminBundle:CRUD:show_date.html.twig
                time:       SonataAdminBundle:CRUD:show_time.html.twig
                datetime:   SonataAdminBundle:CRUD:show_datetime.html.twig
                text:       SonataAdminBundle:CRUD:base_show_field.html.twig
                trans:      SonataAdminBundle:CRUD:show_trans.html.twig
                string:     SonataAdminBundle:CRUD:base_show_field.html.twig
                smallint:   SonataAdminBundle:CRUD:base_show_field.html.twig
                bigint:     SonataAdminBundle:CRUD:base_show_field.html.twig
                integer:    SonataAdminBundle:CRUD:base_show_field.html.twig
                decimal:    SonataAdminBundle:CRUD:base_show_field.html.twig   
                    
sonata_media:
    default_context: default
    db_driver: doctrine_orm 
    contexts:
        default:  # the default context is mandatory
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file

            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}

    cdn:
        server:
            path: /uploads/media # http://media.sonata-project.org/

    filesystem:
        local:
            directory:  %kernel.root_dir%/../web/uploads/media
            create:     false                

sonata_intl:
    timezone:
        # default timezone used as fallback
        default: Europe/Paris

        # locale specific overrides
        locales:
            fr: Europe/Paris  
            
knp_time: ~      # Enable the helper for use in templates            
            
avalanche_imagine:
    driver:       gd
    filters:
        my_thumb:
            type:    thumbnail
            options: { size: [161, 161], mode: outbound, cache_type: public} 
        illustration_last:
            type:    thumbnail
            options: { size: [110, 144], mode: outbound, cache_type: public} 
        illustration_list:
            type:    thumbnail
            options: { size: [100, 130], mode: outbound, cache_type: public} 
        evenement_small:
            type:    thumbnail
            options: { size: [140, 140], mode: outbound, cache_type: public} 
        evenement_medium:
            type:    thumbnail
            options: { size: [300, 200], mode: outbound, cache_type: public} 
        image_small:
            type:    thumbnail
            options: { size: [161, 161], mode: outbound, cache_type: public}
        image_medium:
            type:    thumbnail
            options: { size: [500, 300], mode: outbound, cache_type: public} 
            
fos_comment:
    db_driver: orm
    class:
        model:
            comment: Orchestra\OrchestraBundle\Entity\Comment
            thread: Orchestra\OrchestraBundle\Entity\Thread

assetic:
    bundles: [ "FOSCommentBundle" ]         
    