orchestra_orchestra:
    resource: "@OrchestraOrchestraBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /user 
    
genemu_upload:
    resource: "@GenemuFormBundle/Resources/config/routing/upload.xml"
    
genemu_base64:
    resource: "@GenemuFormBundle/Resources/config/routing/base64.xml"
    
genemu_image:
    resource: "@GenemuFormBundle/Resources/config/routing/image.xml"
    
sonata_page_cache:
    resource: '@SonataCacheBundle/Resources/config/routing/cache.xml'
    prefix: /  
    
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
    
admin_dashboard:
    pattern: /admin
    defaults: { _controller: SonataAdminBundle:Core:dashboard }
    
gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media    
    
orchestra_ldap:
    pattern:    /ldap
    defaults:   { _controller: OrchestraOrchestraBundle:User:ldap }
    
_imagine:
    resource: .
    type:     imagine    