jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_provider:
            chain:
                providers: [fos_userbundle]

        fos_userbundle:
            id: fos_user.user_manager
            
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        main:
            pattern: ^/
            form_login:
                login_path: /login
                provider: chain_provider
                always_use_default_target_path: true
                default_target_path: /profile
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY,}
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY,}
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY,}
        - { path: ^/profile/, role: IS_AUTHENTICATED_ANONYMOUSLY,}
        
        # PAGES ACCESSIBLES AUX ADMINISTRATEURS
        - { path: ^/admin/, role: ROLE_ADMIN,}
        - { path: ^/user/admin/, role: ROLE_ADMIN,}
        
        # PAGES ACCESSIBLES AUX UTILISATEURS CONNECTES
        - { path: ^/change-password/, role: ROLE_USER,}
        - { path: ^/user/, role: ROLE_USER,}
        - { path: ^/salle/, role: ROLE_USER,}
