services:
    orchestra.orchestra.admin.user:
        class: Orchestra\OrchestraBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: orchestra, label: Utilisateur }
        arguments: [null, Orchestra\OrchestraBundle\Entity\User, SonataAdminBundle:CRUD]
    
    orchestra.orchestra.admin.sex:
        class: Orchestra\OrchestraBundle\Admin\SexAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: orchestra, label: Sexe }
        arguments: [null, Orchestra\OrchestraBundle\Entity\Sex, SonataAdminBundle:CRUD]
    
    orchestra.orchestra.admin.salle:
        class: Orchestra\OrchestraBundle\Admin\SalleAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: orchestra, label: Salle }
        arguments: [null, Orchestra\OrchestraBundle\Entity\Salle, SonataAdminBundle:CRUD]
    
    orchestra.orchestra.admin.module:
        class: Orchestra\OrchestraBundle\Admin\ModuleAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: orchestra, label: Module }
        arguments: [null, Orchestra\OrchestraBundle\Entity\Module, SonataAdminBundle:CRUD]
    
    orchestra.orchestra.admin.section:
        class: Orchestra\OrchestraBundle\Admin\SectionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: orchestra, label: Section }
        arguments: [null, Orchestra\OrchestraBundle\Entity\Section, SonataAdminBundle:CRUD]
    
    orchestra.orchestra.admin.news:
        class: Orchestra\OrchestraBundle\Admin\NewsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: orchestra, label: News }
        arguments: [null, Orchestra\OrchestraBundle\Entity\News, SonataAdminBundle:CRUD]
    
    orchestra.orchestra.admin.livre:
        class: Orchestra\OrchestraBundle\Admin\LivreAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: mediatheque, label: Livre }
        arguments: [null, Orchestra\OrchestraBundle\Entity\Livre, SonataAdminBundle:CRUD]
    
    orchestra.orchestra.admin.genre:
        class: Orchestra\OrchestraBundle\Admin\GenreAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: mediatheque, label: Genre }
        arguments: [null, Orchestra\OrchestraBundle\Entity\Genre, SonataAdminBundle:CRUD]
    
    orchestra.orchestra.admin.auteur:
        class: Orchestra\OrchestraBundle\Admin\AuteurAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: mediatheque, label: Auteur }
        arguments: [null, Orchestra\OrchestraBundle\Entity\Auteur, SonataAdminBundle:CRUD]
    
    orchestra.orchestra.admin.galerie:
        class: Orchestra\OrchestraBundle\Admin\GalerieAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: galerie, label: Galerie }
        arguments: [null, Orchestra\OrchestraBundle\Entity\Galerie, SonataAdminBundle:CRUD]
    
    orchestra.orchestra.admin.media:
        class: Orchestra\OrchestraBundle\Admin\MediaAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: galerie, label: Media }
        arguments: [null, Orchestra\OrchestraBundle\Entity\Media, SonataAdminBundle:CRUD]
    
    orchestra.orchestra.admin.image:
        class: Orchestra\OrchestraBundle\Admin\ImageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: galerie, label: Image }
        arguments: [null, Orchestra\OrchestraBundle\Entity\Image, SonataAdminBundle:CRUD]
        
    orchestra_orchestra.form.label_extension:
        class: Orchestra\OrchestraBundle\Form\Extension\LabelFormTypeExtension
        tags:
            -  { name: form:type_extension, alias: field }
        
    bcc.twig.extension:
        class: BCC\ExtraToolsBundle\Twig\TwigExtension
        tags:
            -  { name: twig.extension }
            
    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
           - { name: twig.extension }
 
    twig.extension.intl:
       class: Twig_Extensions_Extension_Intl
       tags:
           - { name: twig.extension }
           
    twig.extension.mytwigextension:  
        class: Orchestra\OrchestraBundle\Extension\MyTwigExtension  
        tags:  
            -  { name: twig.extension } 
 
    debug.twig.extension:
        class: Twig_Extensions_Extension_Debug
        tags: [{ name: 'twig.extension' }] 