services:
    orchestra.orchestra.admin.user:
        class: Orchestra\OrchestraBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: orchestra, label: user }
        arguments: [null, Orchestra\OrchestraBundle\Entity\User, SonataAdminBundle:CRUD]