<?php

namespace Orchestra\OrchestraBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LegalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LegalRepository extends EntityRepository
{
}
