<?php

namespace Orchestra\OrchestraBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SondageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SondageRepository extends EntityRepository
{
}
