<?php

namespace Orchestra\OrchestraBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SpecialityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecialityRepository extends EntityRepository
{
}
